services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nebus-test-task-bd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4.0-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15673:5672"
      - "25673:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    build: .
    command: python -m alembic upgrade head
    env_file: .env.docker
    depends_on:
      postgres:
        condition: service_healthy

  api:
    build: .
    command: python main.py
    env_file: .env.docker
    ports:
      - "8000:8000"
    depends_on:
      migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy

  consumer:
    build: .
    command: python consumer.py
    env_file: .env.docker
    depends_on:
      migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:
