"""add production indexes on payments and outbox status

Revision ID: ea06aac90ee1
Revises: ffb5ed77b50b
Create Date: 2026-09-17 17:26:05.056334

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ea06aac90ee1'
down_revision: Union[str, Sequence[str], None] = 'ffb5ed77b50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_status_created_at'), table_name='outbox')
    op.create_index('ix_outbox_status_id', 'outbox', ['status', 'id'], unique=False)
    op.create_index('ix_payments_status_created_at', 'payments', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_status_created_at', table_name='payments')
    op.drop_index('ix_outbox_status_id', table_name='outbox')
    op.create_index(op.f('ix_outbox_status_created_at'), 'outbox', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###
