"""create payments and outbox tables

Revision ID: ffb5ed77b50b
Revises:
Create Date: 2026-09-17 14:17:42.826950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffb5ed77b50b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
                    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
                    sa.Column('event_type', sa.String(length=100), nullable=False),
                    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
                    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('last_error', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
                    sa.CheckConstraint("status IN ('pending', 'published', 'failed')", name='ck_outbox_status'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_outbox_aggregate_id'), 'outbox', ['aggregate_id'], unique=False)
    op.create_index('ix_outbox_status_created_at', 'outbox', ['status', 'created_at'], unique=False)
    op.create_table('payments',
                    sa.Column('payment_id', sa.String(length=36), nullable=False),
                    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
                    sa.Column('currency', sa.String(length=3), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
                              nullable=True),
                    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
                    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
                    sa.Column('webhook_url', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
                    sa.CheckConstraint("currency IN ('RUB', 'USD', 'EUR')", name='ck_payments_currency'),
                    sa.CheckConstraint("status IN ('pending', 'succeeded', 'failed')", name='ck_payments_status'),
                    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
                    sa.PrimaryKeyConstraint('payment_id'),
                    sa.UniqueConstraint('idempotency_key', name='uq_payments_idempotency_key')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_index('ix_outbox_status_created_at', table_name='outbox')
    op.drop_index(op.f('ix_outbox_aggregate_id'), table_name='outbox')
    op.drop_table('outbox')
    # ### end Alembic commands ###
